### ISSUE TITLE
Build Fail

### ISSUE THREAD

**Issue by acxz** [ros-melodic-arch/ros-melodic-rosbag#1]
```
-- The C compiler identification is GNU 9.2.0
-- The CXX compiler identification is GNU 9.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /home/acxz/.cache/yay/ros-melodic-rosbag/src/build/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/melodic
-- This workspace overlays: /opt/ros/melodic
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.7.4", minimum required is "2") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python3
-- Using default Python package layout
-- Found PY_em: /usr/lib/python3.7/site-packages/em.py  
-- Using empy: /usr/lib/python3.7/site-packages/em.py
-- Using CATKIN_ENABLE_TESTING: ON
-- Skip enable_testing() when building binary package
-- Using CATKIN_TEST_RESULTS_DIR: /home/acxz/.cache/yay/ros-melodic-rosbag/src/build/test_results
-- Found gtest: gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-3.7
-- catkin 0.7.19
-- BUILD_SHARED_LIBS is on
-- Found Boost: /usr/lib64/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components:  date_time regex program_options filesystem 
-- Found BZip2: /usr/lib/libbz2.so (found version "1.0.8") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    PYTHON_BASENAME
    PYTHON_INCLUDE_DIR
    PYTHON_LIBRARY


-- Build files have been written to: /home/acxz/.cache/yay/ros-melodic-rosbag/src/build
Scanning dependencies of target encrypt
[ 10%] Building CXX object CMakeFiles/encrypt.dir/src/encrypt.cpp.o
In file included from /usr/include/boost/config/header_deprecated.hpp:18,
                 from /usr/include/boost/progress.hpp:22,
                 from /home/acxz/.cache/yay/ros-melodic-rosbag/src/ros_comm-1.14.3/tools/rosbag/src/encrypt.cpp:39:
/usr/include/boost/progress.hpp:23:1: note: #pragma message: This header is deprecated. Use the facilities in <boost/timer/timer.hpp> instead.
   23 | BOOST_HEADER_DEPRECATED( "the facilities in <boost/timer/timer.hpp>" )
      | ^~~~~~~~~~~~~~~~~~~~~~~
/usr/include/boost/timer.hpp:21:1: note: #pragma message: This header is deprecated. Use the facilities in <boost/timer/timer.hpp> instead.
   21 | BOOST_HEADER_DEPRECATED( "the facilities in <boost/timer/timer.hpp>" )
      | ^~~~~~~~~~~~~~~~~~~~~~~
/home/acxz/.cache/yay/ros-melodic-rosbag/src/ros_comm-1.14.3/tools/rosbag/src/encrypt.cpp: In function ‘int encrypt(const EncryptorOptions&)’:
/home/acxz/.cache/yay/ros-melodic-rosbag/src/ros_comm-1.14.3/tools/rosbag/src/encrypt.cpp:161:12: error: ‘class rosbag::Bag’ has no member named ‘setEncryptorPlugin’
  161 |     outbag.setEncryptorPlugin(options.plugin, options.param);
      |            ^~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/encrypt.dir/build.make:63: CMakeFiles/encrypt.dir/src/encrypt.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:252: CMakeFiles/encrypt.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
Error making: ros-melodic-rosbag
```

**Comment by acxz** [comment]
upstream issue: https://github.com/ros/ros_comm/issues/1829

**Comment by jwhendy** [comment]
I can't replicate this. I get similar error warnings, but my build succeeds. I'm on:
```
$ git log
commit c0d9d0fcf780477743e01a2acf54884d3129b61d (HEAD -> master, origin/master, origin/HEAD, src-fix)
Author: jwhendy <jw.hendy@gmail.com>
Date:   Sun Sep 15 14:58:13 2019 -0500

    bumped version
```

**Comment by acxz** [comment]
hmmm... I am also on that version.

**Comment by jwhendy** [comment]
Not sure if this is helpful or not, but if you'd like to peruse my build output, it's [here](https://pastebin.com/s9nnn2XP).

**Comment by jwhendy** [comment]
Also, keep in mind that I just got done rebuilding all of ros-melodic-ros-base and ros-melodic-desktop. I have no idea what I'm doing, but the boost thing drove me crazy to I started over :( That said, it makes me wonder if something rosbag depends on is still on boost 1.69?

Can you start by trying to rebuild all of ros-melodic-rosbag deps?

**Comment by jwhendy** [comment]
Also, if you want, you could use [this hacky script](https://pastebin.com/NtEns8qC). It uses `aurutils` to get the depends for a package on AUR, but you specify a local directory where the folders live. This way, it builds locally vs. from AUR directly.

I didn't have success using `subprocess` and `--noconfirm`, so annoyingly you'd have to press enter for each step... but at least it worked 97% successfully to build everything in my cloned repos by just doing (for example):
```
python rebuild.py ros-melodic-ros-base /home/jwhendy/installed/build/ros-melodic-aur
```

Adjust target package and directory accordingly. You could play with the script to force rebuilds and use it on `ros-melodic-rosbag`.

**Comment by acxz** [comment]
I had already done a rebuild of ros-melodic-desktop-full after the boost upgrade and had gotten all of `ros-melodic-desktop-full` building properly with the relevant PRs. This error came up when I was doing a system upgrade and `ros-melodic-rosbag` had gotten upgraded on the AUR. 

Based on the error tho it doesn't seem to be a problem from a dep. Let me dig into the code a bit more and see if there is a method called `setEncryptorPlugin` defined.

Thanks for the script I'll take a look into it.

**Comment by acxz** [comment]
Ah I think I found the issue, `rosbag` depends on `rosbag-storage`. The AUR has `rosbag-storage=1.12.3` but `rosbag=1.14.3`. and `rosbag=1.14.3` needs the latest version of `rosbag-storage` which is not on the AUR. A sync will fix the issue.

**Comment by jwhendy** [comment]
Ah, nice find. And indeed:
```
$ pacman -Q |grep rosbag
ros-melodic-rosbag 1.14.3-1
ros-melodic-rosbag-storage 1.14.3-1
```

**Comment by acxz** [comment]
It weird that `rosbag` got updated on the AUR but it's deps didnt

**Comment by acxz** [comment]
I guess I'll close this since it is a sync issue, but as these issues are coming up more and more I feel like we should have a label for `need to sync` similar to `patched` So we can keep track which packages need to be synced for the AUR packages to build. It would also help @bionade24 figure out which packages to sync if he doesn't want to sync the entire github.

**Comment by bionade24** [comment]
Weird. It wasn't updated for sure, even though the script worked for the other packages. Fixed it now.
